[CMIP6_lgm_tos]
uri = "ssh://albedo1.dmawi.de:/albedo/work/projects/p_pool_clim_data/Paleodata/Tierney2020/LGM/recipe_cmip6_lgm_tos_20241114_151009/preproc/lgm/tos_CLIM"

[herzschuh2023]
uri = "https://doi.pangaea.de/10.1594/PANGAEA.930512?format=zip"
doi = "10.1594/PANGAEA.930512"

[jonkers2024]
uri = "https://download.pangaea.de/dataset/962852/files/LGM_foraminifera_assemblages_20240110.csv"
doi = "10.1594/PANGAEA.962852"

[tierney2020]
uri = "https://github.com/jesstierney/lgmDA/archive/refs/tags/v2.1.zip"
