[herzschuh2021]
doi = "10.1594/PANGAEA.930512"
downloads = ["https://doi.pangaea.de/10.1594/PANGAEA.930512?format=zip"]

[jonkers2024]
doi = "10.1594/PANGAEA.962852"
downloads = ["https://download.pangaea.de/dataset/962852/files/LGM_foraminifera_assemblages_20240110.csv"]

[tierney2020]
remote = "git@github.com:jesstierney/lgmDA.git"